### ISSUE TITLE
I.E11 - After I submit a video, the following error msg appears

### ISSUE THREAD

**Issue by c-schooley** [CCI-Studios/You-Video-Market#35]
![msg](https://cloud.githubusercontent.com/assets/10854834/6620674/629afc7c-c8a8-11e4-88b2-1c4925435ea7.jpg)

**Comment by hemantcci** [comment]
Hey cassie can you try doing it one more time It seems like you were automatically logged out because updated site. RIght now I am updating can please try after sometime.
